# Generated by Django 4.0.4 on 2022-05-04 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_guide_created_at_alter_group_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='guide',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guides', to='api.group'),
        ),
    ]
